### ISSUE TITLE
Adding props/callback to stop prev/next tap

### ISSUE THREAD

**Issue by camunity** [davidramos-om/react-stories-components#1]
Hey bro! 

Great work on getting the clickable prop working on this! Hopefully the team working on r-s-c can get some changes pulled soon. Til then i'm looking to accomplish two things:

1) add clickable buttons to the stories
2) stop the user from tapping to go to prev or next story 

This fork handles the first one but is there some way to add the 2nd option as a set of callbacks to your current distribution? 

I saw this fork of the original repo as well but was having trouble forking it myself. https://github.com/Ezrayter/react-insta-stories/commit/a6734e9b9a03d97b1642c7ab5288a473e6fa809d

Appreciate your help man!

Peace!

Cam

**Comment by davidramos-om** [comment]
Hi there, 

I was very soon to conclude a minor change, so I did. 

Now, you should be able to fulfill your objects. Take a look at the new properties. I think you can do it using the available properties.

[Visit the demo site](https://davidramos-om.github.io/react-stories-components/)

`preventChangeSideTapped : false` should works. If no, try together with `clickable : true`

If you are interested in handling your own nav, check up the sample [here](https://github.com/davidramos-om/react-stories-components/blob/main/example.md)

![image](https://user-images.githubusercontent.com/1109279/124054234-d554be80-d9de-11eb-9146-00b7de08d1c1.png)
